name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-awesome-pages-plugin

      - name: Prepare docs folder
        run: |
          mkdir -p docs
          cp README.md docs/index.md
          cp -r Academics docs/
          cp -r Technology docs/
          cp -r Projects docs/
          cp -r Life docs/
          cp -r stylesheets docs/

      - name: Deploy
        run: mkdocs gh-deploy --force
